import { AfterViewInit, ElementRef, EventEmitter } from '@angular/core';
import * as i0 from "@angular/core";
export declare class NgxColorPaletteComponent implements AfterViewInit {
    private elementRef;
    color: string;
    squared: boolean;
    position: string;
    currentColor: EventEmitter<any>;
    mode: string;
    protected colors: {
        color: string;
        preview: string;
        variants: string[];
    }[];
    protected crayola: {
        hex: string;
        name: string;
        rgb: string;
    }[];
    protected material: {
        red: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        pink: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        purple: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        deeppurple: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        indigo: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        blue: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        lightblue: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        cyan: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        teal: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        green: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        lightgreen: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        lime: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        yellow: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        amber: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        orange: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        deeporange: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
            a100: string;
            a200: string;
            a400: string;
            a700: string;
        };
        brown: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
        };
        grey: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
        };
        bluegrey: {
            "50": string;
            "100": string;
            "200": string;
            "300": string;
            "400": string;
            "500": string;
            "600": string;
            "700": string;
            "800": string;
            "900": string;
        };
    };
    protected choosenColor: string;
    protected isShow: boolean;
    protected isPalette: boolean;
    protected paletteIndex: number;
    protected iterator: number[];
    protected colorAxis: any[];
    protected clientBox: DOMRect;
    protected randomId: string;
    constructor(elementRef: ElementRef);
    ngAfterViewInit(): void;
    protected setColor(color: string): void;
    protected discardCoreColor(): void;
    protected setCoreColor(): void;
    showWheel(): void;
    showHsl(): void;
    showCrayola(): void;
    showBasic(): void;
    showMaterial(): void;
    protected onGlobalClick(event: any): void;
    protected hslToHex(h: any, s: any, l: any): string;
    showColorWheel(): void;
    randomColor(): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<NgxColorPaletteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NgxColorPaletteComponent, "ngx-color-palette", never, { "color": { "alias": "color"; "required": false; }; "squared": { "alias": "squared"; "required": false; }; "position": { "alias": "position"; "required": false; }; }, { "currentColor": "currentColor"; }, never, never, true, never>;
}
